version: "3"
services:
  index:
    container_name: index
    image: nginx
    volumes:
      - .:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.index.entrypoints=https
      - traefik.http.routers.index.tls=true
      - traefik.http.routers.index.tls.certresolver=letsencrypt
      - traefik.http.routers.index.rule=Host(`sqweeb.net`)
      - traefik.http.routers.index.middlewares=redirect-https # redirect http to https

networks:
  proxy:
    external: true