version: "3"
services:
  index:
    container_name: index
    image: nginx
    volumes:
      - ./site/:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - proxy
    labels:
      # enable traefik ingress
      - traefik.enable=true

      # http web ui internal
      - traefik.http.routers.index-int-http.entrypoints=http
      - traefik.http.routers.index-int-http.rule=Host(`tsnet`)

networks:
  proxy:
    external: true
