version: "3"
services:
  dungeons:
    container_name: dungeons
    image: mikeder/dungeons:server
    restart: always
    networks:
      - proxy
    ports:
      - 9080:9080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      # enable traefik ingress
      - traefik.enable=true

      # http web
      - traefik.http.routers.dungeons-http.entrypoints=http
      - traefik.http.routers.dungeons-http.rule=Host(`dungeons.sqweeb.net`)
      - traefik.http.routers.dungeons-http.middlewares=redirect-https # redirect http to https

      # https web
      - traefik.http.routers.dungeons-https.tls=true
      - traefik.http.routers.dungeons-https.entrypoints=https
      - traefik.http.routers.dungeons-https.tls.certresolver=letsencrypt
      - traefik.http.routers.dungeons-https.rule=Host(`dungeons.sqweeb.net`)

networks:
  proxy:
    external:
      name: proxy
