version: "3"
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    restart: unless-stopped
    labels:
      - "traefik.backend=navidrome"
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:music.sqweeb.net"
      - "traefik.port=4533"
    environment:
      ND_SCANSCHEDULE: 1h
      ND_SESSIONTIMEOUT: 24h
    volumes:
      - "/home/meder/navidrome/data:/data"
      - "/home/meder/navidrome/music:/music:ro"
