version: "3"
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: 1000:1000
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.navidrome.entrypoints=https
      - traefik.http.routers.navidrome.tls=true
      - traefik.http.routers.navidrome.tls.certresolver=letsencrypt
      - traefik.http.routers.navidrome.rule=Host(`navidrome.sqweeb.net`)
      - traefik.http.routers.navidrome.middlewares=redirect-https # redirect http to https
    environment:
      ND_SCANSCHEDULE: 1h
      ND_SESSIONTIMEOUT: 24h
      ND_RECENTLYADDEDBYMODTIME: true
    volumes:
      - "/home/meder/homelab/navidrome/data:/data"
      - "/mnt/music:/music:ro"
networks:
  proxy:
    external: true
