version: "3"
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: 1000:1000
    restart: unless-stopped
    networks:
      - proxy
    labels:
      # enable traefik ingress
      - traefik.enable=true

      # http web ui
      - traefik.http.routers.navidrome-http.entrypoints=http
      - traefik.http.routers.navidrome-http.rule=Host(`music.sqweeb.net`)
      - traefik.http.routers.navidrome-http.middlewares=redirect-https # redirect http to https

      # https web ui
      - traefik.http.routers.navidrome-https.tls=true
      - traefik.http.routers.navidrome-https.entrypoints=https
      - traefik.http.routers.navidrome-https.tls.certresolver=letsencrypt
      - traefik.http.routers.navidrome-https.rule=Host(`music.sqweeb.net`)
    environment:
      ND_SCANSCHEDULE: 1h
      ND_SESSIONTIMEOUT: 24h
      ND_RECENTLYADDEDBYMODTIME: "true"
    volumes:
      - "/home/meder/homelab/navidrome/data:/data"
      - "/mnt/music:/music:ro"
networks:
  proxy:
    external: true
