version: '3'
services:
  airsonic:
    container_name: airsonic
    image: airsonicadvanced/airsonic-advanced:latest
    user: 1000:1000 # should be owner of volumes
    restart: unless-stopped
    networks:
      - proxy
    environment:
      CONTEXT_PATH: /
      JAVA_OPTS: -Dserver.use-forward-headers=true -Dserver.context-path=/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airsonic.tls=true"
      - "traefik.http.routers.airsonic.tls.certresolver=http"
      - "traefik.http.routers.airsonic.rule=Host(`airsonic.sqweeb.net`)"
      - "traefik.http.services.airsonic.loadbalancer.server.port=4040"
    volumes:
      - /mnt/music:/var/music
      - /home/meder/homelab/airsonic/data:/var/airsonic
      - /home/meder/homelab/airsonic/playlists:/var/playlists
      - /home/meder/homelab/airsonic/podcasts:/var/podcasts
networks:
  proxy:
    external: true
