version: '3'
services:
  airsonic:
    container_name: airsonic
    image: airsonicadvanced/airsonic-advanced:latest
    user: 1000:1000
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PUID: 1000
      PGID: 1000
      CONTEXT_PATH: /
      JAVA_OPTS: -Dserver.use-forward-headers=true -Dserver.context-path=/
    labels:
      - traefik.enable=true
      - traefik.http.routers.airsonic.tls=true
      - traefik.http.routers.airsonic.tls.certresolver=letsencrypt
      - traefik.http.routers.airsonic.rule=Host(`airsonic.sqweeb.net`)
      - traefik.http.routers.airsonic.middlewares=redirect-https # redirect http to https
      - traefik.http.services.airsonic.loadbalancer.server.port=4040
    volumes:
      - /mnt/music:/var/music
      - /home/meder/homelab/airsonic/data:/var/airsonic
      - /home/meder/homelab/airsonic/playlists:/var/playlists
      - /home/meder/homelab/airsonic/podcasts:/var/podcasts
networks:
  proxy:
    external: true
