version: '3'

services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 8888:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/meder/homelab/traefik/acme.json:/acme.json
      - /home/meder/homelab/traefik/traefik.yml:/traefik.yml
      - /home/meder/homelab/traefik/rules.yml:/rules.yml
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
networks:
  proxy:
    external: true
