version: '3'

services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 1900:1900/udp
      - 4041:4041/udp
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/meder/homelab/traefik/acme.json:/acme.json
      - /home/meder/homelab/traefik/traefik.yml:/traefik.yml
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
      - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.rule=Host(`sqweeb.net`)
      - traefik.http.routers.traefik.middlewares=redirect-https # redirect http to https
      - traefik.http.routers.traefik-secure.entrypoints=https
      - traefik.http.routers.traefik-secure.rule=Host(`sqweeb.net`)
      - traefik.http.routers.traefik-secure.tls=true
      - traefik.http.routers.traefik-secure.tls.certresolver=letsencrypt
networks:
  proxy:
    external: true
