log:
  level: DEBUG

api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/rules.yml"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: sqweebking@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: http
