log:
  level: DEBUG

api:
  insecure: true
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  airsonic-dlna:
    address: ":4041/udp"
  upnp:
    address: ":1900/udp"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: sqweebking@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: http
