apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clicker-pg-data
  namespace: homelab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clicker-db
  namespace: homelab
spec:
  serviceName: clicker-db
  replicas: 1
  selector:
    matchLabels:
      app: clicker-db
  template:
    metadata:
      labels:
        app: clicker-db
    spec:
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: shitlist
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clicker-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: clicker-pg-data
---
apiVersion: v1
kind: Service
metadata:
  name: clicker-db
  namespace: homelab
spec:
  selector:
    app: clicker-db
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
