version: "3"
services:
  clicker:
    container_name: clicker
    image: mikeder/clicker:latest
    restart: always
    env_file:
      - .env
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      # enable traefik ingress
      - traefik.enable=true

      # http web
      - traefik.http.routers.clicker-http.entrypoints=http
      - traefik.http.routers.clicker-http.rule=Host(`click.sqweeb.net`)
      - traefik.http.routers.clicker-http.middlewares=redirect-https # redirect http to https

      # https web
      - traefik.http.routers.clicker-https.tls=true
      - traefik.http.routers.clicker-https.entrypoints=https
      - traefik.http.routers.clicker-https.tls.certresolver=letsencrypt
      - traefik.http.routers.clicker-https.rule=Host(`click.sqweeb.net`)

  db:
    image: postgres:latest
    restart: always
    volumes:
      - /home/meder/homelab/clicker/data:/var/lib/postgresql/data
    networks:
      - proxy
    environment:
      POSTGRES_DB: shitlist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretPW

  migrate:
    image: mikeder/clicker:latest-migrate
    restart: on-failure
    networks:
      - proxy

networks:
  proxy:
    external:
      name: proxy
