version: "3"

services:
  netdash:
    cap_add:
      - NET_RAW
    container_name: netdash
    environment:
      NETDASH_SUBNET: 192.168.1
      NETDASH_INTERFACE: ens18
    image: ghcr.io/mikeder/netdash:main
    restart: unless-stopped
    networks:
      - proxy
    labels:
      # enable traefik ingress
      - traefik.enable=true

      # http web ui
      - traefik.http.routers.netdash-http.entrypoints=http
      - traefik.http.routers.netdash-http.rule=Host(`netdash.sqweeb.net`)
      - traefik.http.routers.netdash-http.middlewares=redirect-https # redirect http to https

      # https web ui
      - traefik.http.routers.netdash-https.tls=true
      - traefik.http.routers.netdash-https.entrypoints=https
      - traefik.http.routers.netdash-https.tls.certresolver=letsencrypt
      - traefik.http.routers.netdash-https.rule=Host(`netdash.sqweeb.net`)

networks:
  proxy:
    external: true
