version: "3.1"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    networks:
      - proxy 
    expose:
      - "9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/meder/docker/portainer_data:/data"
    labels:
      - "traefik.backend=portainer"
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.protocol=http"
      - "traefik.docker.network=proxy"
      - "traefik.frontend.rule=Host:docker.sqweeb.net"

  globber:
    container_name: globber
    image: mikeder/globber:latest
    restart: always
    networks:
      - proxy
    environment:
      GLOBBER_DBNAME: <SNIP>
      GLOBBER_DBHOST: <SNIP>
      GLOBBER_DBUSER: <SNIP>
      GLOBBER_DBPASS: <SNIP>
      GLOBBER_SITENAME: <SNIP>
      GLOBBER_TOKENSECRET: <SNIP> 
      GLOBBER_MINECRAFTHOST: <SNIP>
    expose:
      - "3000"
    labels:
      - "traefik.backend=globber"
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.protocol=http"
      - "traefik.docker.network=proxy"
      - "traefik.frontend.rule=Host:sqweeb.net,www.sqweeb.net"

#  oldblog:
#    container_name: oldblog
#    image: mikeder/tornado-blog:latest
#    restart: always
#    environment:
#      MYSQL_DATABASE: <SNIP>
#      MYSQL_HOST: <SNIP>
#      MYSQL_USER: <SNIP>
#      MYSQL_PASSWORD: <SNIP>
#    networks:
#      - proxy
#    expose:
#      - "8000"
#    labels:
#      - "traefik.backend=oldblog"
#      - "traefik.enable=true"
#      - "traefik.port=8000"
#      - "traefik.protocol=http"
#      - "traefik.docker.network=proxy"
#      - "traefik.frontend.rule=Host:www.sqweeb.net,old.blog.sqweeb.net,sqweeb.net"

networks:
  proxy:
    external:
      name: proxy
