version: "3.1"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    networks:
      - proxy 
    expose:
      - "9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/meder/docker/portainer_data:/data"
    labels:
      - "traefik.backend=portainer"
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.protocol=http"
      - "traefik.docker.network=proxy"
      - "traefik.frontend.rule=Host:docker.sqweeb.net"

networks:
  proxy:
    external:
      name: proxy
