version: "3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/meder/docker/portainer_data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.entrypoints=https
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=letsencrypt
      - traefik.http.routers.portainer.rule=Host(`docker.sqweeb.net`)
      - traefik.http.routers.portainer.middlewares=redirect-https # redirect http to https
      - traefik.http.services.portainer.loadbalancer.server.port=9000
networks:
  proxy:
    external:
      name: proxy
