version: "3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/meder/homelab/portainer/portainer_data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer-http.entrypoints=http
      - traefik.http.routers.portainer-http.service=portainer
      - traefik.http.routers.portainer-http.rule=Host(`docker.sqweeb.net`)
      - traefik.http.routers.portainer-http.middlewares=redirect-https # redirect http to https
      - traefik.http.routers.portainer-https.tls=true
      - traefik.http.routers.portainer-https.entrypoints=https
      - traefik.http.routers.portainer-https.service=portainer
      - traefik.http.routers.portainer-https.tls.certresolver=letsencrypt
      - traefik.http.routers.portainer-https.rule=Host(`docker.sqweeb.net`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
networks:
  proxy:
    external:
      name: proxy
