---
version: "2.1"
services:
  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - /home/meder/homelab/unifi/config:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      # - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
    labels:
      # enable traefik ingress
      - traefik.enable=true
      - traefik.http.services.unifi.loadbalancer.server.port=8443

      # https web ui
      - traefik.http.routers.unifi-http.service=unifi
      - traefik.http.routers.unifi-http.entrypoints=http
      - traefik.http.routers.unifi-http.rule=Host(`unifi.sqweeb.net`)
      - traefik.http.routers.unifi-http.middlewares=redirect-https # redirect http to https

      # https web ui
      - traefik.http.routers.unifi-https.tls=true
      - traefik.http.routers.unifi-https.service=unifi
      - traefik.http.routers.unifi-https.entrypoints=https
      - traefik.http.routers.unifi-https.tls.certresolver=letsencrypt
      - traefik.http.routers.unifi-https.rule=Host(`unifi.sqweeb.net`)
networks:
  proxy:
    external:
      name: proxy
