services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      ENABLE_ROLLING_LOGS: "true"
      EULA: "TRUE"
      MAX_PLAYERS: "10"
      MEMORY: "3G"
      TYPE: "PAPER"
      TZ: "America/New_York"
      USE_AIKAR_FLAGS: "true"
      VERSION: "26.3"
    volumes:
      - /home/meder/homelab/minecraft/data:/data
    # keep stdin/tty open so `docker attach minecraft` gives a server console
    stdin_open: true
    tty: true
