version: "3"

services:
  runner:
    image: docker.io/gitea/act_runner:nightly
    depends_on:
      server:
        condition: service_started
    environment:
      GITEA_INSTANCE_URL: "https://git.sqweeb.net"
      GITEA_RUNNER_REGISTRATION_TOKEN: ${GITEA_RUNNER_REGISTRATION_TOKEN}
      GITEA_RUNNER_NAME: "local"
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
  server:
    image: docker.io/gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
    labels:
      # enable traefik ingress
      - traefik.enable=true

      # http web ui
      - traefik.http.routers.gittea-http.entrypoints=http
      - traefik.http.routers.gittea-http.rule=Host(`git.sqweeb.net`)
      - traefik.http.routers.gittea-http.middlewares=redirect-https # redirect http to https

      # https web ui
      - traefik.http.routers.gittea-https.tls=true
      - traefik.http.routers.gittea-https.entrypoints=https
      - traefik.http.routers.gittea-https.tls.certresolver=letsencrypt
      - traefik.http.routers.gittea-https.rule=Host(`git.sqweeb.net`)
      - traefik.http.services.gittea.loadbalancer.server.port=3000

networks:
  proxy:
    external: true
