version: "3"

services:
  server:
    image: docker.io/gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
    labels:
      # enable traefik ingress
      - traefik.enable=true

      # http web ui
      - traefik.http.routers.gittea-http.entrypoints=http
      - traefik.http.routers.gittea-http.rule=Host(`git.sqweeb.net`)
      - traefik.http.routers.gittea-http.middlewares=redirect-https # redirect http to https

      # https web ui
      - traefik.http.routers.gittea-https.tls=true
      - traefik.http.routers.gittea-https.entrypoints=https
      - traefik.http.routers.gittea-https.tls.certresolver=letsencrypt
      - traefik.http.routers.gittea-https.rule=Host(`git.sqweeb.net`)
      - traefik.http.services.gittea.loadbalancer.server.port=3000

networks:
  proxy:
    external: true
